### ISSUE TITLE
set time

### ISSUE THREAD

**Issue by JCTaz9** [unix-witch/LOL-banner#1]
Hey how do i set the time so its different than 30min?

**Comment by SmilerRyan** [comment]
> Hey how do i set the time so its different than 30min?

Looking through the code, the bot seems to ban as soon as it detects their status change. As for adding a timer to this, you could make a list of all people detected playing this game (contains userid/timestamp), and checking the list again when their status changes to see if it's been at least 30 minutes. After they finish and close the game, turn off their status or go offline, that's when it will trigger the ban.
